apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "factory-edge.fullname" . }}-mosquitto
  namespace: {{ .Values.namespace }}
data:
  mosquitto.conf: |
    persistence true
    persistence_location /mosquitto/data/

    listener 1883 0.0.0.0
    allow_anonymous true

    log_type all
    log_dest stdout
