apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "factory-edge.fullname" . }}-mqtt
  namespace: {{ .Values.namespace }}
  labels:
    app: factory-edge
    component: mqtt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: factory-edge
      component: mqtt
  template:
    metadata:
      labels:
        app: factory-edge
        component: mqtt
    spec:
      containers:
        - name: mosquitto
          image: {{ .Values.images.mosquitto }}
          ports:
            - name: mqtt
              containerPort: 1883
          volumeMounts:
            - name: mosquitto-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
      volumes:
        - name: mosquitto-config
          configMap:
            name: {{ include "factory-edge.fullname" . }}-mosquitto
