apiVersion: v1
kind: Secret
metadata:
  name: {{ include "factory-edge.fullname" . }}-db
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.db.name | quote }}
  POSTGRES_USER: {{ .Values.db.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.password | quote }}
