apiVersion: v1
kind: Service
metadata:
  name: {{ include "factory-edge.fullname" . }}-mqtt
  namespace: {{ .Values.namespace }}
  labels:
    app: factory-edge
    component: mqtt
spec:
  selector:
    app: factory-edge
    component: mqtt
  ports:
    - name: mqtt
      port: 1883
      targetPort: mqtt
