apiVersion: v1
kind: Service
metadata:
  name: {{ include "factory-edge.fullname" . }}-connector
  namespace: {{ .Values.namespace }}
  labels:
    app: factory-edge
    component: connector
spec:
  selector:
    app: factory-edge
    component: connector
  ports:
    - name: http-metrics
      port: 8000
      targetPort: http
