apiVersion: v1
kind: Service
metadata:
  name: {{ include "factory-edge.fullname" . }}-db
  namespace: {{ .Values.namespace }}
  labels:
    app: factory-edge
    component: db
spec:
  selector:
    app: factory-edge
    component: db
  ports:
    - name: pg
      port: 5432
      targetPort: pg
